apps/users/urls.py
from django.urls import path, include

from . import views
from apps.users.views import *

app_name = 'user'

urlpatterns = [
    path('', ListUserPerfil.as_view(), name='user_profile'),
    path('followers/', ListUserFollowers.as_view(), name='user_followers'),
    path('following/', ListUserFollowing.as_view(), name='user_following'),
    path('stories-subscription/', ListStoriesSubscription.as_view(),
         name='user_stories_subscription'),
    path('follow/', FollowUser.as_view(), name='user_follow'),
    path('unfollow/', UnfollowUser.as_view(), name='user_unfollow'),
    path('delete/<int:id>', DeleteUser.as_view(), name='user_delete'),
    path('publication/', include('apps.publications.urls')),
    path('search/<suser>', SearchUser.as_view(), name='user_search'),
    path('edit-account/', EditUserAccount.as_view(), name='edit_account'),
    path('edit-profile/', EditUserProfile.as_view(), name='edit_profile'),

]

storylink_dev/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic.base import TemplateView
from apps.users.views import SignUpView, mail_check, username_check, \
    FillProfile, VerifiedMail, CustomLoginView, SignUpApiConnectorView

from apps.users.api.views import UserViewSet, UserProfileViewSet, \
    FullUserDataViewSet, WhoamiViewSet

from apps.publications.api.views import StoryPublicationViewSet, \
    StoryChapterViewSet

from apps.users.views import ReactV, B2CViewSet
from apps.publications.views import ListStories


from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
# import routers
from rest_framework import routers

# define the router
router = routers.DefaultRouter()

# define the router path and viewset to be used
router.register('users', UserViewSet)
router.register('profiles', UserProfileViewSet)
router.register('full-users', FullUserDataViewSet)
router.register('stories', StoryPublicationViewSet)
router.register('chapters', StoryChapterViewSet)
router.register('whoami', WhoamiViewSet, basename='whoami')

API_VERSION = 1

api_urls = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('', include(router.urls)),
]

urlpatterns = [
    path('success/<success>', CustomLoginView.as_view(),
         name='hall_s'),  # pagina principal
    path('activated/<activated>', ListStories.as_view(),
         name='hall_a'),  # pagina principal
    path('', ListStories.as_view(), name='hall'),  # pagina principal
    path('admin/site/', admin.site.urls),
    # matchea con un string despues del .com/ y termina de procesarlo en el archivo urls de users
    path('users/<str:username>/', include('apps.users.urls')),
    path('migrate/', include('apps.userMigrator.urls')),
    # para iniciar sesion con el formulario que permite usuarios inactivos
    path('accounts/login/', CustomLoginView.as_view(), name="custom_login"),
    # para la administracion de la cuenta de usuario
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', SignUpView.as_view(), name='sign_up'),
    path('signup-connector/', SignUpApiConnectorView.as_view(), name='sign_up_connector'),
    path('terminos_privacidad/',
         TemplateView.as_view(template_name='term_priv.html'),  name='term_priv'),
    path('social/', include('social_django.urls', namespace='social')),
    path('re_email/', mail_check.as_view(), name='form_new_mail'),
    path('re_username/', username_check.as_view(), name='form_new_username'),
    path('fillprofile/<uidb64>/', FillProfile.as_view(), name='fill_profile'),
    path('fillprofile/<uidb64>/<email_verified>',
         FillProfile.as_view(), name='fill_profile'),
    path('activate/<uidb64>/<token>', VerifiedMail.as_view(), name='activate'),
    path('api/v%d/b2c' % (API_VERSION), B2CViewSet.as_view(), name='b2c'),
    path('api/v%d/' % (API_VERSION), include(api_urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>{% block title-page %}S{% endblock %}</title>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-162832086-1"></script>

    <link rel="stylesheet" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Material icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'base/css/theater.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/custom.css' %}">
    <link rel="icon" type="image/png" href="{% static 'imgs/story_minim.png' %}" sizes="32x32">
    {% block head-page %}{% endblock %}
    <script>
        {% if user.is_authenticated %}
        js_user_id = {{ user.profile.get.id }};
        {% endif %}
    </script>
    <!-- Facebook Pixel Code -->
    <noscript><img height="1" width="1" style="display:none"
            src="https://www.facebook.com/tr?id=2674235692866237&ev=PageView&noscript=1" /></noscript>
    <!-- End Facebook Pixel Code -->
</head>

<body>
    <div id="page-container">
        {%block primary-navbar%}
        <div id="header-base" class="sticky-top">
            <small style="color:white; margin:auto;">Beta</small>
            <!-- navBar primario -->
            <div class="container">
                <nav id="primary-navbar" class="navbar navbar-expand-lg navbar-dark">
                    <!-- Brand -->
                    <a class="navbar-brand" href="/"><img id="logo" src="{% static 'imgs/ostorylink_blank.png' %}"
                            alt="Story Link logo"></a>
                    <!-- Collapse button -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#collapsibleNavbarPrimary">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Links -->
                    {% if user.is_authenticated %}
                    <div class="collapse navbar-collapse" id="collapsibleNavbarPrimary">
                        <form id="form-search" class="form-inline" action="">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="material-icons">search</i></span>
                                </div>
                                <input id="input-search" autocomplete="off"
                                    onkeyup="searchUser('{% url 'user:user_profile' user.username %}')"
                                    onfocus="searchUser('{% url 'user:user_profile' user.username %}')" type="text"
                                    class="form-control" placeholder="Nombre de usuario">
                                <div id="users-found"></div>
                            </div>
                        </form>
                        <a class="nav-link nav-hall" href="/">Hall</a>
                    </div>
                    {%endif%}
                    <div id="login-div">
                        {% if user.is_authenticated %}
                        <a href="{%url 'user:user_profile' user.username %}">
                            <img class="nav-img-perfil" src="{{ user.profile.get.link_img_perfil.url }}"
                                alt="img perfil">
                            {{user.username}}
                        </a>
                        <div class="dropdown">
                            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            </button>
                            <div class="dropdown-menu" style="right: 0;left: initial;"
                                aria-labelledby="dropdownMenuLink">
                                <a href="{% url 'user:edit_account' user.username %}">Configuración</a>
                                <div class="dropdown-divider"></div>
                                <a href="{% url 'logout' %}">Cerrar sesión</a>
                            </div>
                        </div>
                        {% else %}
                        <a class="" href="{% url 'sign_up' %}">Registrarse</a>
                        <a class="" href="{% url 'login' %}">Iniciar Sesión</a>
                        {% endif %}
                    </div>
                </nav>
            </div>
        </div>
        {%endblock%}
        <!--primary-navbar-->

        <div id="base-div">
            {% block main-content%}

            {%endblock%}
            <!--main-content -->
            {% block display-pub-detail %}
            {% include "publications/story/theater_mode.html" %}
            {% endblock %}
        </div>
        {% include "modal_alert.html" %}
    </div>

    <footer id="footer">
        <div class="container d-flex">
            <img id="storylink-pin" src="{% static 'imgs/storylink_ulti_opt.svg' %}" alt="Storylink logo">
            <ul id="data-contact">
                <li>Contacto: storylink@hotmail.com</li>
            </ul>
        </div>
        <p style="text-align: center"><small>Este sitio está en Beta, estamos trabajando continuamente para
                mejorarlo.</small></p>
    </footer>
    <script src="{% static 'base/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'base/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.3.1-dist/js/bootstrap.min.js' %}"></script>
    <!-- Smooth Scroll to Link -->
    <script src="{% static 'publication/js/scroll_smooth.js' %}"></script>
    <script src="{% static 'base/js/base.js' %}"></script>

    {% block extra-script%}

    {%endblock%}
    <!--extras scripts -->

    <div class="cookies">
        <div class="container">
            <h4 class="cookies__titulo">Aceptar Cookies?</h4>
            <p class="cookies__texto">Usamos cookies para mejorar tu experiencia en la web.</p>
        </div>
        <div class="container d-flex justify-content-around">
            <a href="javascript: void(0)" class="cookies__boton cookies__boton--no">Declinar</a>
            <a href="javascript: void(0)" class="cookies__boton cookies__boton--si">Aceptar</a>
        </div>
    </div>

</body>

</html>

templates/modal_alert.html
<div class="modal fade" id="modal-alert" tabindex="-1" role="dialog" aria-labelledby="modal-alert-title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-alert-title">Title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

templates/test.html
{% load static %}
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <div id="app"></div>
     <script>
      window.django = {
        urls: {
          login: "{% url 'login' %}",
          logout: "{% url 'logout' %}"        },
        user: {
          authenticated: {% autoescape off %}("True" === "{{ user.is_authenticated }}"){% endautoescape %},
          username: "{{ request.user.username }}",
        }
      };
    </script>

    {% render_bundle 'main' %}
</body>
</html>