apps/users/urls.py
from django.urls import path, include

from . import views
from apps.users.views import *

app_name = 'user'

urlpatterns = [
    path('', ListUserPerfil.as_view(), name='user_profile'),
    path('followers/', ListUserFollowers.as_view(), name='user_followers'),
    path('following/', ListUserFollowing.as_view(), name='user_following'),
    path('stories-subscription/', ListStoriesSubscription.as_view(),
         name='user_stories_subscription'),
    path('follow/', FollowUser.as_view(), name='user_follow'),
    path('unfollow/', UnfollowUser.as_view(), name='user_unfollow'),
    path('delete/<int:id>', DeleteUser.as_view(), name='user_delete'),
    path('publication/', include('apps.publications.urls')),
    path('search/<suser>', SearchUser.as_view(), name='user_search'),
    path('edit-account/', EditUserAccount.as_view(), name='edit_account'),
    path('edit-profile/', EditUserProfile.as_view(), name='edit_profile'),

]

storylink_dev/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic.base import TemplateView
from apps.users.views import SignUpView, mail_check, username_check, \
    FillProfile, VerifiedMail, CustomLoginView, SignUpApiConnectorView

from apps.users.api.views import UserViewSet, UserProfileViewSet, \
    FullUserDataViewSet, WhoamiViewSet

from apps.publications.api.views import StoryPublicationViewSet, \
    StoryChapterViewSet

from apps.users.views import ReactV, B2CViewSet
from apps.publications.views import ListStories


from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
# import routers
from rest_framework import routers

# define the router
router = routers.DefaultRouter()

# define the router path and viewset to be used
router.register('users', UserViewSet)
router.register('profiles', UserProfileViewSet)
router.register('full-users', FullUserDataViewSet)
router.register('stories', StoryPublicationViewSet)
router.register('chapters', StoryChapterViewSet)
router.register('whoami', WhoamiViewSet, basename='whoami')

API_VERSION = 1

api_urls = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('', include(router.urls)),
]

urlpatterns = [
    path('success/<success>', CustomLoginView.as_view(),
         name='hall_s'),  # pagina principal
    path('activated/<activated>', ListStories.as_view(),
         name='hall_a'),  # pagina principal
    path('', ListStories.as_view(), name='hall'),  # pagina principal
    path('admin/site/', admin.site.urls),
    # matchea con un string despues del .com/ y termina de procesarlo en el archivo urls de users
    path('users/<str:username>/', include('apps.users.urls')),
    path('migrate/', include('apps.userMigrator.urls')),
    # para iniciar sesion con el formulario que permite usuarios inactivos
    path('accounts/login/', CustomLoginView.as_view(), name="custom_login"),
    # para la administracion de la cuenta de usuario
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', SignUpView.as_view(), name='sign_up'),
    path('signup-connector/', SignUpApiConnectorView.as_view(), name='sign_up_connector'),
    path('terminos_privacidad/',
         TemplateView.as_view(template_name='term_priv.html'),  name='term_priv'),
    path('social/', include('social_django.urls', namespace='social')),
    path('re_email/', mail_check.as_view(), name='form_new_mail'),
    path('re_username/', username_check.as_view(), name='form_new_username'),
    path('fillprofile/<uidb64>/', FillProfile.as_view(), name='fill_profile'),
    path('fillprofile/<uidb64>/<email_verified>',
         FillProfile.as_view(), name='fill_profile'),
    path('activate/<uidb64>/<token>', VerifiedMail.as_view(), name='activate'),
    path('api/v%d/b2c' % (API_VERSION), B2CViewSet.as_view(), name='b2c'),
    path('api/v%d/' % (API_VERSION), include(api_urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/users/api/views.py
# import viewsets
from rest_framework import viewsets

# import local data
from .serializers import UserSerializer, UserProfileSerializer, \
    FullUserDataSerializer, WhoamiSerializer
from ..models import CustomUser, UserProfile

from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

class UserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer
    permission_classes = (IsAuthenticated,)


class WhoamiViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = WhoamiSerializer
    permission_classes = (IsAuthenticated,)
    basename = 'whoami'

    def get_queryset(self):
        return CustomUser.objects.filter(username=self.request.user.username)


class UserProfileViewSet(viewsets.ModelViewSet):
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer


class FullUserDataViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = FullUserDataSerializer

apps/users/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic, View
from django.contrib.auth import login, authenticate
from apps.publications.models import StoryPublication, StoryChapter
from apps.users.models import CustomUser, UserProfile
from apps.users.forms import CustomUserCreationForm, MailCheck, UsernameCheck,\
     CreateUserProfile, AuthenticationFormWithInactiveUsersOkay
from apps.users.forms import EditUserProfile as EditUserProfileForm,\
    EditAccount
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.db import transaction, IntegrityError
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from .token import account_activation_token
from django.core.mail import EmailMessage

from django.conf import settings
import base64
from azure_ad_verify_token import verify_jwt


def getPayload(self, request):
    azure_ad_app_id = 'c23486d4-c9ee-4e7f-b0ef-8a5222db50b5'
    azure_ad_issuer = 'https://storylinkb2c.b2clogin.com/tfp/8f366d86-6d3f-43f5-81e1-d84cd7bd349b/b2c_1_reactjs_susin/v2.0/'
    azure_ad_jwks_uri = 'https://storylinkb2c.b2clogin.com/storylinkb2c.onmicrosoft.com/b2c_1_reactjs_susin/discovery/v2.0/keys'
    return verify_jwt(
        token="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsifQ.eyJpc3MiOiJodHRwczovL3N0b3J5bGlua2IyYy5iMmNsb2dpbi5jb20vdGZwLzhmMzY2ZDg2LTZkM2YtNDNmNS04MWUxLWQ4NGNkN2JkMzQ5Yi9iMmNfMV9yZWFjdGpzX3N1c2luL3YyLjAvIiwiZXhwIjoxNjEyMDE2Mzc3LCJuYmYiOjE2MTIwMTI3NzcsImF1ZCI6ImMyMzQ4NmQ0LWM5ZWUtNGU3Zi1iMGVmLThhNTIyMmRiNTBiNSIsIm9pZCI6IjNmODZhZDI0LTJkNjUtNDZkZi05YWQyLTNjYjViMDg2M2IzMCIsInN1YiI6IjNmODZhZDI0LTJkNjUtNDZkZi05YWQyLTNjYjViMDg2M2IzMCIsImdpdmVuX25hbWUiOiJNYXJ0aW4iLCJmYW1pbHlfbmFtZSI6IkJlcm11ZGV6IiwibmFtZSI6InVua25vd24iLCJlbWFpbHMiOlsiYmVybXVkZXpfbWFydGluLm5xbkBob3RtYWlsLmNvbSJdLCJ0ZnAiOiJCMkNfMV9yZWFjdGpzX3N1c2luIiwibm9uY2UiOiI4YTU2M2FmNi0xMmNlLTQ3YTItYTI0Ni0wNjQzZWEwMzUwMDkiLCJzY3AiOiJGaWxlcy5SZWFkIiwiYXpwIjoiY2JjYTJkMzgtZmE2OC00MjM2LWJkYmEtZjk3ZmMwY2ZmYjlkIiwidmVyIjoiMS4wIiwiaWF0IjoxNjEyMDEyNzc3fQ.fbkzxgVhbcnJisHHbapBsbMI5gGFlx0K4U2A_Dti7atzVMx_YqhXKYupMdWL-cVlxHUgrN9dxaL9WmO6YatLWhj4ykQzt91EjUGn9iDkXHn3BPK7mxnHHkt1MtVqE4D-5L1cDYG__W5ws2Q-PRwF5Wgt8Ry7g1CgG0GBSKIqXQYLcmhqz8vf7QI9tc7KqqzncwEmaIMRxDqGAELm17wvxMixtVq5-VAkTdPnR55C_2bdBv2PefPbgndOUjcWGfdK8vnZwAXqSUDGCc3Jo03yV7X79uVUS4C8C2daw4woeg37vUi1s3s6Dm2U1bMUSyfw-zu910K3Gr9gZGG8YiAEZg",
        valid_audiences=[azure_ad_app_id],
        issuer=azure_ad_issuer,
        jwks_uri=azure_ad_jwks_uri,
    )


class B2CViewSet(View):

    def get(self, request):
        data = dict()
        pay = getPayload(self, request)
        data.update({'payload': pay})
        return JsonResponse(data)


class ReactV(generic.TemplateView):
    template_name = 'test.html'

# retorna el perfil del usuario


class ListUserPerfil(LoginRequiredMixin, generic.DetailView):
    model = CustomUser
    template_name = 'users/user_profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_object(self):
        return get_object_or_404(
            CustomUser,
            username=self.kwargs.get('username'), is_active=True)

    def get_context_data(self, **kwargs):
        context = super(ListUserPerfil, self).get_context_data(**kwargs)
        from_user = self.request.user
        to_user = self.get_object()
        is_following = from_user.profile.get().from2To.filter(
            to_user=to_user.profile.get()).exists()
        context.update({'is_following': is_following})
        context.update({'customuser': to_user})
        publications = StoryPublication.objects.get_stories_by_user(
            to_user, from_user).order_by('date_time__month', '-date_time__day')
        context.update({'storypublication_list': publications})
        chaps = StoryChapter.objects.get_chapters_by_user(
            to_user, from_user).order_by('date_time__month', '-date_time__day')
        context.update({'storychapter_list': chaps})
        return context

# para listar los followers


class ListUserFollowers(LoginRequiredMixin, generic.DetailView):
    template_name = 'users/followers.html'
    model = CustomUser
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super(ListUserFollowers, self).get_context_data(**kwargs)
        followers = self.object.profile.get().to2From.all()
        context.update({'followers': followers})
        return context


# para listar los followings
class ListUserFollowing(LoginRequiredMixin, generic.DetailView):
    template_name = 'users/following.html'
    model = CustomUser
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super(ListUserFollowing, self).get_context_data(**kwargs)
        following = self.object.profile.get().from2To.all()
        context.update({'following': following})
        return context


# para listar las subscripciones a stories de un usuario
class ListStoriesSubscription(LoginRequiredMixin, generic.ListView):
    template_name = 'publications/story/story_subscription.html'
    models = StoryPublication
    paginate_by = 10

    def get_queryset(self):
        user = get_object_or_404(CustomUser, username=self.kwargs["username"])
        qs = user.profile.get().pub_subscription.filter(active=True)
        return qs

# agregar seguidor a user.


class FollowUser(LoginRequiredMixin, generic.DetailView):
    model = CustomUser
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get(self, request, username):
        self.request.user.profile.get().user_subscription.add(
            self.get_object().profile.get())
        return redirect(reverse_lazy('user:user_profile',
                                     kwargs={'username': username}))

# unfollow user


class UnfollowUser(LoginRequiredMixin, generic.DetailView):
    model = CustomUser
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get(self, request, username):
        self.request.user.profile.get().user_subscription.remove(
            self.get_object().profile.get())
        return redirect(reverse_lazy('user:user_profile',
                                     kwargs={'username': username}))


class SignUpView(generic.CreateView):
    '''para dar de alta un usuario. Cuando crea el usuario le envia un mail
    para verificar la cuenta.'''
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'registration/login.html'

    def get_context_data(self, **kwargs):
        context = super(SignUpView, self).get_context_data(**kwargs)
        context.update({'formSignUp': self.get_form()})
        context.update({'formLogin': AuthenticationFormWithInactiveUsersOkay})
        return context

    def post(self, request, *args, **kwargs):
        print(request.POST)
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        send_mail_confirm(self.request, user)
        return redirect(reverse_lazy('hall_s', kwargs={'success': True}))


class SignUpApiConnectorView(generic.CreateView):
    ''' API connector para azure b2c.
    Da de alta un usuario y retorna su userID.'''
    model = CustomUser
    form_class = CustomUserCreationForm

    def post(self, request, *args, **kwargs):
        #auth_header = request.META.get('HTTP_AUTHORIZATION', '')
        #token_type, _, credentials = auth_header.partition(' ')
        token_type, _, credentials = 'Basic YWRtaW4xOjEyMzQ1'.partition(' ')
        base64_bytes = credentials.encode('ascii')
        message_bytes = base64.b64decode(base64_bytes)
        message = message_bytes.decode('ascii')
        username, password = message.split(':')
        if (token_type != 'Basic' or
                username != settings.API_CONNECTOR_BASIC_AUTHENTICATION_USER or
                password !=
                settings.API_CONNECTOR_BASIC_AUTHENTICATION_PASSWORD):
            return JsonResponse(status=401)
        else:
            return super().post(request, *args, **kwargs)

    def form_invalid(self, form):
        resp = dict()
        resp.update({'status': 400})
        body = dict()
        body.update({
            'version': 1.0,
            'action': "ValidationError",
            'status': 400,
            'userMessage': form.errors.as_json(),
            'code': "SingUp-Input-Validation-0"})
        resp.update({'body': body})
        return JsonResponse(resp, status=400)

    def form_valid(self, form):
        user = form.save()
        resp = dict()
        resp.update({
            'version': 1.0,
            'action': 'continue',
            'extension_8fe2c4d0-5118-4a84-a0bc-04a9b8ec6a76_userID': user.pk})
        return JsonResponse(resp)


class CustomLoginView(generic.edit.FormView):
    '''CustomloginView permite iniciar sesion solo si un usuario
     tiene el email verificado y ademas tiene el UserProfile creado
     (no checkea is_active en CustomUser).
     Si el email no esta verificado el formulario lanza is_invalid.
     Si el mail esta verificado y el usuario aun no tiene creado
     su UserProfile, entonces se lo redirige a FillProfile para que pueda
     crear su profile.
     Si el usuario tiene el mail verificado, y se inicia sesion,
     se verifica si su estado era activo o inactivo, para actualizarlo.'''

    form_class = AuthenticationFormWithInactiveUsersOkay
    template_name = 'registration/login.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(CustomLoginView, self).get_context_data(**kwargs)

templates/users/edit_account.html
{% extends "users/user_profile.html" %}

{% load static %}
{% block title-page %}{{customuser.first_name}} {{customuser.last_name}}{% endblock %}
{% block head-page-extra %}
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'publication/css/custom.css' %}">
<!-- Icons star CSS -->
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
{% endblock %}

{% block profile-side-left %}
<div class="container" id="profile-description">
    <ul class="edit-menu">
      <li><a href="{% url 'user:edit_account' user.username %}">Configuración general</a></li>
      <li><a href="{% url 'user:edit_profile' user.username %}">Configuración de perfil</a></li>
    </ul>
</div>
{%endblock%}

templates/users/edit_profile.html
{% extends "users/edit_account.html" %}
{% load widget_tweaks %}
{% load static %}
{% block title-page %}{{customuser.first_name}} {{customuser.last_name}}{% endblock %}

{% block profile-body %}
<div id="title-profile-body" class="justify-content-center">
  <h2>Configuración del perfil</h2>
</div>
<div class="container" id="container-form-create-account">
  <hr>
  <form class="form-create-user" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}
        {%if not field.field.required or field.id_for_label|stringformat:"s" == "id_link_img_perfil" %}
            <span class="not-required-field">*</span>
        {%endif%}
        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}
    <div class="row justify-content-center">
    <button type="submit" class="btn-custom-2">Guardar cambios</button>
    </div>
  </form>
  <small class="form-text text-muted">* Campo no obligatorio</small>
</div>
{%endblock%}

templates/users/edit_user_account.html
{% extends "users/edit_account.html" %}
{% load widget_tweaks %}
{% load static %}
{% block title-page %}{{customuser.first_name}} {{customuser.last_name}}{% endblock %}

{% block profile-body %}
<div id="title-profile-body" class="justify-content-center">
  <h2>Configuración general de la cuenta</h2>
</div>
<div class="container" id="container-form-create-account">
  <hr>
  <form class="form-create-user" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}
        {%if not field.field.required or field.id_for_label|stringformat:"s" == "id_link_img_perfil" %}
            <span class="not-required-field">*</span>
        {%endif%}
        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}
    <div class="row justify-content-center">
    <button type="submit" class="btn-custom-2">Guardar cambios</button>
    </div>
  </form>
  <small class="form-text text-muted">* Campo no obligatorio</small>
</div>
{%endblock%}

templates/users/followers.html
{% extends "users/profile_base.html" %}
{% load static %}

{% block title-page %}Seguidores de {{customuser.first_name}} {{customuser.last_name}}{% endblock %}

{% block profile-body %}
<div class="row">
    <div class="users-preview col">
        {% for p in followers %}
        {% include "users/user_card_base.html" with profile=p.from_user %}
        {% endfor %}
    </div>
</div>
{%endblock%}

templates/users/following.html
{% extends "users/profile_base.html" %}
{% load static %}

{% block title-page %}Usuarios seguidos por {{customuser.first_name}} {{customuser.last_name}}{% endblock %}

{% block profile-body %}
<div class="row">
    <div class="users-preview col">
        {% for p in following %}
        {% include "users/user_card_base.html" with profile=p.to_user %}
        {% endfor %}
    </div>
</div>
{%endblock%}

templates/users/profile_base.html
{% extends "base.html" %}
{% load static %}
{% block title-page %} {{customuser.username}}{% endblock %}
{% block head-page %}
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'user/css/custom.css' %}">
{%block head-page-extra%}{% endblock %}
{% endblock %}
{% block main-content %}
{% block profile-menu %}

<!-- navBar secundario -->
<div class="temporal-div">
    <nav class="temporal-nav">
        <ul class="">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:user_profile' customuser.username%}">Perfil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:user_stories_subscription' customuser.username%}">Suscripciones</a>
            </li>
            {%if customuser.username == user.username %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:pub:create_story' customuser.username%}">Crear Storylink</a>
            </li>
            {%endif%}
        </ul>
    </nav>
    <nav id="nav-profile" class="navbar navbar-expand-md navbar-dark" >
    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbarSecundary">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbarSecundary">
        <ul class="navbar-nav">
            {%comment%}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:pub:user_stories_own' customuser.username%}">Publicaciones</a>
            </li> 
            <!--<li class="nav-item">
                <a class="nav-link" href="{% url 'user:pub:user_resources_own' customuser.username%}">Recursos</a>
            </li>--> 

            {%if customuser.username == user.username %}
            <li class="nav-item">
                <a class="nav-link" href="#">Borradores</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Novedades</a>
            </li>
            <li class="nav-item">
                <!--<a class="nav-link" href="{% url 'user:pub:create_resource' customuser.username%}">Crear Resource</a>
                </li>-->
                {%endif%}
                {%endcomment%}
                <li class="nav-item">
                    <a class="" href="{% url 'user:user_followers' customuser.username%}">Seguidores</a>
                </li> 
                <li class="nav-item">
                    <a class="" href="{% url 'user:user_following' customuser.username%}">Siguiendo</a>
                </li>

            </ul>
        </div>
    </nav>
    </div>
    {%endblock%}

    <div class="container" id="profile-content">
        {% block profile-content %}
        <div class="row justify-content-center">
        <div class="col-lg-12" id="container-profile-body">
            <div class="container" id="profile-body">
                {% block profile-body %}
                {%endblock%}
            </div>
        </div>
    </div>
    {%endblock%}
    

</div>

{% endblock %}

{%block extra-script%}
<script src="{% static 'publication/js/publication_display.js' %}"></script>
{% endblock %}

templates/users/user_card_base.html
<div class="card-user ">
    <div class="card-thumbnail">
        <img class="img-thumbnail" src="{{ profile.link_img_perfil.url }}" alt="User image">
    </div>
    <div class="card-body-user">
        <p>                
            <a href="{% url 'user:user_profile' profile.user.username %}">{{profile.user.username}}</a>
        </p>
    </div>
</div>

templates/users/user_profile.html
{% extends "users/profile_base.html" %}

{% load static %}
{% block title-page %}{{customuser.first_name}} {{customuser.last_name}}{% endblock %}
{% block head-page-extra %}
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'publication/css/custom.css' %}">
<!-- Icons star CSS -->
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
{% endblock %}

{% block profile-content %}
<div class="row">
    <div class="col-sm-12 col-lg-4" id="profile-side-left">
        {% block profile-side-left %}
        <div class="container" id="profile-description">
            {% block profile-description %}
            <ul>
                <li>
                    <img alt="Imagen de perfil" class="img-perfil" src="{{ customuser.profile.get.link_img_perfil.url }}">
                </li> 
                <li>
                    <a href="{% url 'user:user_profile' customuser.username %}">{{customuser.first_name}} {{customuser.last_name}}</a>
                </li>
                <li>
                    {{customuser.profile.get.description}}
                </li>     
                <li>
                    {{customuser.tags}}
                </li>
                {%if user.username != customuser.username %}      
                <li>
                    {%if is_following%}
                    <a href="{%url 'user:user_unfollow' customuser.username %}">Dejar de seguir</a>
                    {%else%}
                    <a href="{%url 'user:user_follow' customuser.username %}">Seguir</a>
                    {%endif%}
                </li>
                {%endif%}
            </ul>
            {%endblock%}
        </div>
        {%endblock%}
    </div>
    <div class="col-sm-12 col-lg-8" id="container-profile-body">
        <div class="container" id="profile-body">
            {% block profile-body %}
            <div id="title-profile-body" class="justify-content-center">
            <h2>Publicaciones de {{customuser.username}} </h2>
            </div>

            <div class="row">
                <div class="stories-preview col-12">
                    {%if storypublication_list or storychapter_list%}
                        {% include "publications/story/list_stories_chapters.html" %}
                    {%else%}
                      {%if customuser.username != user.username%}
                        <div class="empy-pub"><h5>{{customuser.username}} no ha escrito ninguna Storylink!</h5></div>
                      {%else%}
                        <div class="empy-pub"><h5>No has escrito ninguna Storylink, animate!</h5></div>
                      {%endif%}
                  {%endif%}
                </div>
            </div>
            {%endblock%}
        </div>
    </div>
</div>
{%endblock%}